theme = "noctalia"
# See the full configuration reference: https://rioterm.com/docs/config

[editor]
program = "hx"
args = []

[fonts]
size = 16
features = []
use-drawable-chars = true
# symbol-map = [{ start = "2297", end = "2299", font-family = "MesloLGS NF" }]
disable-warnings-not-found = false
additional-dirs = []

[fonts.regular]
family = "Fira Code"
style = "default"

[fonts.bold]
family = "Fira Code"
style = "default"

[fonts.italic]
family = "Fira Code"
style = "default"

[fonts.bold-italic]
family = "Fira Code"
style = "default"

[window]
opacity =0.90
# blur = false

[bindings]
keys = [
  { key = "tab", with = "control", action = "SelectNextSplitOrTab" },
  { key = "tab", with = "control | shift", action = "SelectPrevSplitOrTab" },
  # Enable VI mode on escape, when not in VI mode.
  { key = "esc", mode = "vi", action = "ToggleVIMode" }
]
