[accessibility]
ui_scale = 1.1000000089406967

[backdrop]
blur_intensity = 0.1099999975413084
enabled = true
tint_intensity = 0.0

[bar]
order = [ "default" ]

    [bar.default]
    capsule = true
    center = [ "clock", "date", "widget", "shelly" ]
    end = [
        "media",
        "tray",
        "notifications",
        "clipboard",
        "network",
        "bluetooth",
        "volume",
        "brightness",
        "battery",
        "control-center",
        "cpu",
        "temp",
        "session"
    ]
    font_family = "Overpass Nerd Font Propo"
    font_weight = 300
    margin_ends = 0.0
    panel_overlap = -2
    scale = 1.5000000149011612
    start = [ "launcher", "wallpaper", "workspaces", "notes", "check_repos" ]

[control_center]
sidebar = "full"

[dock]
launcher_position = "start"
reserve_space = false
smart_auto_hide = true

[idle]
behavior_order = [ "lock", "screen-off", "suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

    [idle.behavior.suspend]
    action = "suspend"
    enabled = false
    lock_before_suspend = true
    timeout = 900

[location]
address = "Trondheim, Norway"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DVI-I-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DVI-I-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 1720.0
    cy = 1321.0
    output = "DVI-I-1"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DVI-I-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 768.5601806640625
    cy = 730.6458740234375
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugin_settings."tphilippot/git_companion"]
group = "oskretc"

[plugins]
enabled = [ "noctalia/notes", "weinguyen/procmon", "blackbartblues/keymap", "joshuaslate/shelly", "tphilippot/git_companion" ]

[shell]
font_family = "Cantarell"
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
ui_scale = 1.2500000111758709

    [shell.panel]
    clipboard_placement = "attached"
    transparency_mode = "soft"

[theme]
builtin = "Gruvbox"
source = "community"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "gtk3", "gtk4", "helix", "niri", "wezterm" ]
    community_ids = [ "vicinae", "fastfetch", "zathura", "zellij", "bat", "lazygit", "rio", "yazi" ]

[wallpaper]
directory = "/home/osto/Pictures/Wallpapers"
fill_mode = "stretch"

    [wallpaper.default]
    path = "/home/osto/Pictures/Wallpapers/undefined - Imgur.png"

    [wallpaper.last]
    path = "/home/osto/Pictures/Wallpapers/undefined - Imgur.png"

    [wallpaper.monitors.DVI-I-1]
    path = "/home/osto/Pictures/Wallpapers/undefined - Imgur.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/osto/Pictures/Wallpapers/undefined - Imgur.png"

[weather]
address = "Trondheim"

[widget.check_repos]
glyph = "brand-github"
type = "custom_button"

    [widget.check_repos.actions]
    left = "exec checknotifygit.sh"

[widget.launcher]
glyph = "send"

[widget.notes]
type = "noctalia/notes:notes"

[widget.shelly]
type = "joshuaslate/shelly:shelly"

[widget.widget]
type = "blackbartblues/keymap:widget"

[widget.workspaces]
empty_color = "tertiary"
max_label_chars = 10
scale = 1.5
style = "focus_hint"
