[colors]
background       = '#161616'
foreground       = '#f2f4f8'
cursor           = '#f2f4f8'
vi-cursor        = '#42be65'

black            = '#262626'
red              = '#ee5396'
green            = '#42be65'
yellow           = '#82cfff'
blue             = '#33b1ff'
magenta          = '#ff7eb6'
cyan             = '#3ddbd9'
white            = '#dde1e6'

dim-foreground   = '#f2f4f8'
dim-black        = '#262626'
dim-red          = '#ee5396'
dim-green        = '#42be65'
dim-yellow       = '#82cfff'
dim-blue         = '#33b1ff'
dim-magenta      = '#ff7eb6'
dim-cyan         = '#3ddbd9'
dim-white        = '#dde1e6'

light-foreground = '#f2f4f8'
light-black      = '#393939'
light-red        = '#ee5396'
light-green      = '#42be65'
light-yellow     = '#82cfff'
light-blue       = '#33b1ff'
light-magenta    = '#ff7eb6'
light-cyan       = '#3ddbd9'
light-white      = '#ffffff'

tabs             = '#262626'
tabs-active      = '#42be65'
bar              = '#f2f4f8'
split            = '#262626'

# Search
search-match-background          = '#33b1ff'
search-match-foreground          = '#262626'
search-focused-match-background  = '#42be65'
search-focused-match-foreground  = '#262626'

# Hints
hint-foreground  = '#262626'
hint-background  = '#82cfff'

# Selection
selection-foreground = '#161616'
selection-background = '#f2f4f8'
