[colors]
background       = '#19120b'
foreground       = '#f0e0d4'
cursor           = '#f0e0d4'
vi-cursor        = '#ffbf83'

black            = '#534436'
red              = '#ffb4ab'
green            = '#ffbf83'
yellow           = '#f0bd8e'
blue             = '#c7d559'
magenta          = '#ffb873'
cyan             = '#f0bd8e'
white            = '#f0e0d4'

dim-foreground   = '#f0e0d4'
dim-black        = '#534436'
dim-red          = '#ffb4ab'
dim-green        = '#ffbf83'
dim-yellow       = '#f0bd8e'
dim-blue         = '#c7d559'
dim-magenta      = '#ffb873'
dim-cyan         = '#f0bd8e'
dim-white        = '#f0e0d4'

light-foreground = '#f0e0d4'
light-black      = '#a18d7c'
light-red        = '#ffb4ab'
light-green      = '#ffbf83'
light-yellow     = '#f0bd8e'
light-blue       = '#c7d559'
light-magenta    = '#ffb873'
light-cyan       = '#f0bd8e'
light-white      = '#f0e0d4'

tabs             = '#534436'
tabs-active      = '#ffbf83'
bar              = '#f0e0d4'
split            = '#534436'

# Search
search-match-background          = '#c7d559'
search-match-foreground          = '#534436'
search-focused-match-background  = '#ffbf83'
search-focused-match-foreground  = '#534436'

# Hints
hint-foreground  = '#534436'
hint-background  = '#f0bd8e'

# Selection
selection-foreground = '#d9c2b0'
selection-background = '#534436'
