[colors]
background       = '#151515'
foreground       = '#e0e0e0'
cursor           = '#e0e0e0'
vi-cursor        = '#8c977d'

black            = '#151515'
red              = '#b66467'
green            = '#8c977d'
yellow           = '#d9bc8c'
blue             = '#8da3b9'
magenta          = '#a988b0'
cyan             = '#8aa6a2'
white            = '#e0e0e0'

dim-foreground   = '#e0e0e0'
dim-black        = '#151515'
dim-red          = '#b66467'
dim-green        = '#8c977d'
dim-yellow       = '#d9bc8c'
dim-blue         = '#8da3b9'
dim-magenta      = '#a988b0'
dim-cyan         = '#8aa6a2'
dim-white        = '#e0e0e0'

light-foreground = '#e0e0e0'
light-black      = '#414141'
light-red        = '#b66467'
light-green      = '#8c977d'
light-yellow     = '#d9bc8c'
light-blue       = '#8da3b9'
light-magenta    = '#a988b0'
light-cyan       = '#8aa6a2'
light-white      = '#e8e3e3'

tabs             = '#151515'
tabs-active      = '#8c977d'
bar              = '#e0e0e0'
split            = '#151515'

# Search
search-match-background          = '#8da3b9'
search-match-foreground          = '#151515'
search-focused-match-background  = '#8c977d'
search-focused-match-foreground  = '#151515'

# Hints
hint-foreground  = '#151515'
hint-background  = '#d9bc8c'

# Selection
selection-foreground = '#e0e0e0'
selection-background = '#222222'
