git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --syntax-theme base16-256 -s
keybinding:
  universal:
    prevItem-alt: e
    nextItem-alt: n
    edit: o
gui:
  theme:
    activeBorderColor:
      - "#ffbf83"
      - bold
    inactiveBorderColor:
      - "#f0bd8e"
    searchingActiveBorderColor:
      - "#c7d559"
      - bold
    optionsTextColor:
      - "#d9c2b0"
    selectedLineBgColor:
      - "#312821"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#d9c2b0"
    cherryPickedCommitBgColor:
      - "#c7d559"
    markedBaseCommitFgColor:
      - "#c7d559"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#f0e0d4"
