git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --syntax-theme base16-256 -s
keybinding:
  universal:
    prevItem-alt: e
    nextItem-alt: n
    edit: o
gui:
  theme:
    activeBorderColor:
      - "#8da3b9"
      - bold
    inactiveBorderColor:
      - "#8aa6a2"
    searchingActiveBorderColor:
      - "#a988b0"
      - bold
    optionsTextColor:
      - "#b0b0b0"
    selectedLineBgColor:
      - "#2c2c2c"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#b0b0b0"
    cherryPickedCommitBgColor:
      - "#a988b0"
    markedBaseCommitFgColor:
      - "#a988b0"
    markedBaseCommitBgColor:
      - "#b66467"
    unstagedChangesColor:
      - "#b66467"
    defaultFgColor:
      - "#e8e3e3"
