[colors]
background = '#101418'
foreground = '#e1e2e8'

cursor_bg = '#9fcafc'
cursor_fg = '#101418'
cursor_border = '#9fcafc'

selection_bg = '#174974'
selection_fg = '#e1e2e8'

ansi = ['#101418', '#ff729c', '#7efc8f', '#fff772', '#85b6ef', '#254a74', '#9fcafc', '#eff6ff']
brights = ['#979da3', '#ff9fbb', '#a5ffb1', '#fffaa5', '#afd3ff', '#bddbff', '#d4e8ff', '#f8fbff']
