[colors]
background = '#111318'
foreground = '#e1e2e9'

cursor_bg = '#a5c8fe'
cursor_fg = '#111318'
cursor_border = '#a5c8fe'

selection_bg = '#214876'
selection_fg = '#e1e2e9'

ansi = ['#111318', '#ff729b', '#7ffe91', '#fff872', '#8bb3f1', '#2a4775', '#a5c8fe', '#eff5ff']
brights = ['#989da5', '#ff9fba', '#a5ffb2', '#fffaa5', '#b3d0ff', '#c0d9ff', '#d6e6ff', '#f8fbff']
